spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp
    # spring jpa ??
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # 자바 @Column(name=" ")속성 생략, 자바 필드명 카멜케이스를 언더바로 자동 변환기능

#       ddl-auto: create
       # ㄴ 테이블 만들어가면서 엔티티 속성이 어떻게 변화하는지 보기 위해 create
       # 실제 테이블 create는 X, 모델링과정이 일반적인 상황이다.